package pojos;
// Generated 14-nov-2018 9:41:42 by Hibernate Tools 4.3.1.Final

/**
 * Administrador generated by hbm2java
 */
public class Administrador implements java.io.Serializable {

	private Integer idAdministrador;
	private String nombre;
	private String apellido;
	private Integer telefono;
	private String email;

	public Administrador() {
	}

	public Administrador(String nombre, String apellido, Integer telefono, String email) {
		this.nombre = nombre;
		this.apellido = apellido;
		this.telefono = telefono;
		this.email = email;
	}

	public Integer getIdAdministrador() {
		return this.idAdministrador;
	}

	public void setIdAdministrador(Integer integer) {
		this.idAdministrador = integer;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public Integer getTelefono() {
		return this.telefono;
	}

	public void setTelefono(Integer telefono) {
		this.telefono = telefono;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public void setIdAdministrador(String parameter) {
		// TODO Auto-generated method stub
		
	}

	public void setTelefono(String parameter) {
		// TODO Auto-generated method stub
		
	}

}
