package pojos;
// Generated 26-nov-2018 16:00:00 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private Integer id;
	private Usuario usuario;
	private int fono;
	private int sueldo;
	private String direccionParticular;
	private String direccionLaboral;
	private Date creadoEl;
	private Set<Credito> creditos = new HashSet<Credito>(0);

	public Cliente() {
	}

	public Cliente(int fono, int sueldo, String direccionParticular, String direccionLaboral, Date creadoEl) {
		this.fono = fono;
		this.sueldo = sueldo;
		this.direccionParticular = direccionParticular;
		this.direccionLaboral = direccionLaboral;
		this.creadoEl = creadoEl;
	}

	public Cliente(Usuario usuario, int fono, int sueldo, String direccionParticular, String direccionLaboral,
			Date creadoEl, Set<Credito> creditos) {
		this.usuario = usuario;
		this.fono = fono;
		this.sueldo = sueldo;
		this.direccionParticular = direccionParticular;
		this.direccionLaboral = direccionLaboral;
		this.creadoEl = creadoEl;
		this.creditos = creditos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public int getFono() {
		return this.fono;
	}

	public void setFono(int fono) {
		this.fono = fono;
	}

	public int getSueldo() {
		return this.sueldo;
	}

	public void setSueldo(int sueldo) {
		this.sueldo = sueldo;
	}

	public String getDireccionParticular() {
		return this.direccionParticular;
	}

	public void setDireccionParticular(String direccionParticular) {
		this.direccionParticular = direccionParticular;
	}

	public String getDireccionLaboral() {
		return this.direccionLaboral;
	}

	public void setDireccionLaboral(String direccionLaboral) {
		this.direccionLaboral = direccionLaboral;
	}

	public Date getCreadoEl() {
		return this.creadoEl;
	}

	public void setCreadoEl(Date creadoEl) {
		this.creadoEl = creadoEl;
	}

	public Set<Credito> getCreditos() {
		return this.creditos;
	}

	public void setCreditos(Set<Credito> creditos) {
		this.creditos = creditos;
	}

}
