package pojos;
// Generated 26-nov-2018 16:00:00 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Credito generated by hbm2java
 */
public class Credito implements java.io.Serializable {

	private Integer id;
	private Cliente cliente;
	private Usuario usuario;
	private String folio;
	private int monto;
	private int numCuotas;
	private boolean estado;
	private Date creadoEl;
	private Date aprobadoEl;
	private Date entregadoEl;

	public Credito() {
	}

	public Credito(Cliente cliente, Usuario usuario, String folio, int monto, int numCuotas, boolean estado,
			Date creadoEl) {
		this.cliente = cliente;
		this.usuario = usuario;
		this.folio = folio;
		this.monto = monto;
		this.numCuotas = numCuotas;
		this.estado = estado;
		this.creadoEl = creadoEl;
	}

	public Credito(Cliente cliente, Usuario usuario, String folio, int monto, int numCuotas, boolean estado,
			Date creadoEl, Date aprobadoEl, Date entregadoEl) {
		this.cliente = cliente;
		this.usuario = usuario;
		this.folio = folio;
		this.monto = monto;
		this.numCuotas = numCuotas;
		this.estado = estado;
		this.creadoEl = creadoEl;
		this.aprobadoEl = aprobadoEl;
		this.entregadoEl = entregadoEl;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getFolio() {
		return this.folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

	public int getMonto() {
		return this.monto;
	}

	public void setMonto(int monto) {
		this.monto = monto;
	}

	public int getNumCuotas() {
		return this.numCuotas;
	}

	public void setNumCuotas(int numCuotas) {
		this.numCuotas = numCuotas;
	}

	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	public Date getCreadoEl() {
		return this.creadoEl;
	}

	public void setCreadoEl(Date creadoEl) {
		this.creadoEl = creadoEl;
	}

	public Date getAprobadoEl() {
		return this.aprobadoEl;
	}

	public void setAprobadoEl(Date aprobadoEl) {
		this.aprobadoEl = aprobadoEl;
	}

	public Date getEntregadoEl() {
		return this.entregadoEl;
	}

	public void setEntregadoEl(Date entregadoEl) {
		this.entregadoEl = entregadoEl;
	}

}
