package pojos;
// Generated 14-nov-2018 9:41:42 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Credito generated by hbm2java
 */
public class Credito implements java.io.Serializable {

	private Integer idSolicitud;
	private Cliente cliente;
	private String direccionTrabajo;
	private int montoSolicitado;
	private int numeroCuota;
	private Date fechaAutorizacion;
	private Date fechaEntraga;
	private Boolean estado;

	public Credito() {
	}

	public Credito(Cliente cliente, String direccionTrabajo, int montoSolicitado, int numeroCuota) {
		this.cliente = cliente;
		this.direccionTrabajo = direccionTrabajo;
		this.montoSolicitado = montoSolicitado;
		this.numeroCuota = numeroCuota;
	}

	public Credito(Cliente cliente, String direccionTrabajo, int montoSolicitado, int numeroCuota,
			Date fechaAutorizacion, Date fechaEntraga, Boolean estado) {
		this.cliente = cliente;
		this.direccionTrabajo = direccionTrabajo;
		this.montoSolicitado = montoSolicitado;
		this.numeroCuota = numeroCuota;
		this.fechaAutorizacion = fechaAutorizacion;
		this.fechaEntraga = fechaEntraga;
		this.estado = estado;
	}

	public Integer getIdSolicitud() {
		return this.idSolicitud;
	}

	public void setIdSolicitud(Integer idSolicitud) {
		this.idSolicitud = idSolicitud;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public String getDireccionTrabajo() {
		return this.direccionTrabajo;
	}

	public void setDireccionTrabajo(String direccionTrabajo) {
		this.direccionTrabajo = direccionTrabajo;
	}

	public int getMontoSolicitado() {
		return this.montoSolicitado;
	}

	public void setMontoSolicitado(int montoSolicitado) {
		this.montoSolicitado = montoSolicitado;
	}

	public int getNumeroCuota() {
		return this.numeroCuota;
	}

	public void setNumeroCuota(int numeroCuota) {
		this.numeroCuota = numeroCuota;
	}

	public Date getFechaAutorizacion() {
		return this.fechaAutorizacion;
	}

	public void setFechaAutorizacion(Date fechaAutorizacion) {
		this.fechaAutorizacion = fechaAutorizacion;
	}

	public Date getFechaEntraga() {
		return this.fechaEntraga;
	}

	public void setFechaEntraga(Date fechaEntraga) {
		this.fechaEntraga = fechaEntraga;
	}

	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

}
