package pojos;
// Generated 14-nov-2018 9:41:42 by Hibernate Tools 4.3.1.Final

/**
 * Ejecutivo generated by hbm2java
 */
public class Ejecutivo implements java.io.Serializable {

	private Integer idEjecutivo;
	private Persona persona;
	private String claveEjecutivo;

	public Ejecutivo() {
	}

	public Ejecutivo(Persona persona, String claveEjecutivo) {
		this.persona = persona;
		this.claveEjecutivo = claveEjecutivo;
	}

	public Integer getIdEjecutivo() {
		return this.idEjecutivo;
	}

	public void setIdEjecutivo(Integer idEjecutivo) {
		this.idEjecutivo = idEjecutivo;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public String getClaveEjecutivo() {
		return this.claveEjecutivo;
	}

	public void setClaveEjecutivo(String claveEjecutivo) {
		this.claveEjecutivo = claveEjecutivo;
	}

}
