package pojos;
// Generated 14-nov-2018 9:41:42 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable {

	private String rutPersona;
	private String primerNombre;
	private String segundoNombre;
	private String apePaterno;
	private String apeMaterno;
	private int telefono;
	private String direccion;
	private String coreeo;
	private Date fechaIngresoBanco;
	private int sueldo;
	private Set sucursals = new HashSet(0);
	private Set clientes = new HashSet(0);
	private Set ejecutivos = new HashSet(0);
	private Set supervisors = new HashSet(0);

	public Persona() {
	}

	public Persona(String rutPersona, String primerNombre, String segundoNombre, String apePaterno, String apeMaterno,
			int telefono, String direccion, String coreeo, int sueldo) {
		this.rutPersona = rutPersona;
		this.primerNombre = primerNombre;
		this.segundoNombre = segundoNombre;
		this.apePaterno = apePaterno;
		this.apeMaterno = apeMaterno;
		this.telefono = telefono;
		this.direccion = direccion;
		this.coreeo = coreeo;
		this.sueldo = sueldo;
	}

	public Persona(String rutPersona, String primerNombre, String segundoNombre, String apePaterno, String apeMaterno,
			int telefono, String direccion, String coreeo, Date fechaIngresoBanco, int sueldo, Set sucursals,
			Set clientes, Set ejecutivos, Set supervisors) {
		this.rutPersona = rutPersona;
		this.primerNombre = primerNombre;
		this.segundoNombre = segundoNombre;
		this.apePaterno = apePaterno;
		this.apeMaterno = apeMaterno;
		this.telefono = telefono;
		this.direccion = direccion;
		this.coreeo = coreeo;
		this.fechaIngresoBanco = fechaIngresoBanco;
		this.sueldo = sueldo;
		this.sucursals = sucursals;
		this.clientes = clientes;
		this.ejecutivos = ejecutivos;
		this.supervisors = supervisors;
	}

	public String getRutPersona() {
		return this.rutPersona;
	}

	public void setRutPersona(String rutPersona) {
		this.rutPersona = rutPersona;
	}

	public String getPrimerNombre() {
		return this.primerNombre;
	}

	public void setPrimerNombre(String primerNombre) {
		this.primerNombre = primerNombre;
	}

	public String getSegundoNombre() {
		return this.segundoNombre;
	}

	public void setSegundoNombre(String segundoNombre) {
		this.segundoNombre = segundoNombre;
	}

	public String getApePaterno() {
		return this.apePaterno;
	}

	public void setApePaterno(String apePaterno) {
		this.apePaterno = apePaterno;
	}

	public String getApeMaterno() {
		return this.apeMaterno;
	}

	public void setApeMaterno(String apeMaterno) {
		this.apeMaterno = apeMaterno;
	}

	public int getTelefono() {
		return this.telefono;
	}

	public void setTelefono(int telefono) {
		this.telefono = telefono;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getCoreeo() {
		return this.coreeo;
	}

	public void setCoreeo(String coreeo) {
		this.coreeo = coreeo;
	}

	public Date getFechaIngresoBanco() {
		return this.fechaIngresoBanco;
	}

	public void setFechaIngresoBanco(Date fechaIngresoBanco) {
		this.fechaIngresoBanco = fechaIngresoBanco;
	}

	public int getSueldo() {
		return this.sueldo;
	}

	public void setSueldo(int sueldo) {
		this.sueldo = sueldo;
	}

	public Set getSucursals() {
		return this.sucursals;
	}

	public void setSucursals(Set sucursals) {
		this.sucursals = sucursals;
	}

	public Set getClientes() {
		return this.clientes;
	}

	public void setClientes(Set clientes) {
		this.clientes = clientes;
	}

	public Set getEjecutivos() {
		return this.ejecutivos;
	}

	public void setEjecutivos(Set ejecutivos) {
		this.ejecutivos = ejecutivos;
	}

	public Set getSupervisors() {
		return this.supervisors;
	}

	public void setSupervisors(Set supervisors) {
		this.supervisors = supervisors;
	}

}
