package pojos;
// Generated 14-nov-2018 9:41:42 by Hibernate Tools 4.3.1.Final

/**
 * Sucursal generated by hbm2java
 */
public class Sucursal implements java.io.Serializable {

	private Integer idJefe;
	private Persona persona;
	private String claveJefe;

	public Sucursal() {
	}

	public Sucursal(Persona persona, String claveJefe) {
		this.persona = persona;
		this.claveJefe = claveJefe;
	}

	public Integer getIdJefe() {
		return this.idJefe;
	}

	public void setIdJefe(Integer idJefe) {
		this.idJefe = idJefe;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public String getClaveJefe() {
		return this.claveJefe;
	}

	public void setClaveJefe(String claveJefe) {
		this.claveJefe = claveJefe;
	}

}
