package pojos;
// Generated 14-nov-2018 9:41:42 by Hibernate Tools 4.3.1.Final

/**
 * Supervisor generated by hbm2java
 */
public class Supervisor implements java.io.Serializable {

	private Integer idSupervisor;
	private Persona persona;
	private String claveSupervisor;

	public Supervisor() {
	}

	public Supervisor(Persona persona, String claveSupervisor) {
		this.persona = persona;
		this.claveSupervisor = claveSupervisor;
	}

	public Integer getIdSupervisor() {
		return this.idSupervisor;
	}

	public void setIdSupervisor(Integer idSupervisor) {
		this.idSupervisor = idSupervisor;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public String getClaveSupervisor() {
		return this.claveSupervisor;
	}

	public void setClaveSupervisor(String claveSupervisor) {
		this.claveSupervisor = claveSupervisor;
	}

}
